# This code is part of a Qiskit project.
#
# (C) Copyright IBM 2021, 2023.
#
# This code is licensed under the Apache License, Version 2.0. You may
# obtain a copy of this license in the LICENSE.txt file in the root directory
# of this source tree or at http://www.apache.org/licenses/LICENSE-2.0.
#
# Any modifications or derivative works of this code must retain this
# copyright notice, and modified files need to carry a notice indicating
# that they have been altered from the originals.

name: 'Install Main Dependencies'
description: 'Installs Python dependencies from Main'
inputs:
  os:
    description: 'OS'
    required: true
  python-version:
    description: 'Python version'
    required: true

runs:
  using: "composite"
  steps:
    - name: Get main last commit ids
      run: |
        echo "QISKIT_HASH=$(git ls-remote --heads https://github.com/Qiskit/qiskit.git refs/heads/main  | awk '{print $1}')" >> $GITHUB_ENV
      shell: bash
    - name: Qiskit Cache
      env:
        CACHE_VERSION: v1
      id: qiskit-cache
      uses: actions/cache@v4
      with:
        path: qiskit-cache
        key: qiskit-cache-${{ inputs.os }}-${{ inputs.python-version }}-${{ env.QISKIT_HASH }}-${{ env.CACHE_VERSION }}
    - name: Install Qiskit from Main
      env:
        MACOSX_DEPLOYMENT_TARGET: 10.15
      run: |
        echo 'Install Qiskit from Stable'
        pip install -U qiskit
      shell: bash
